server:
  port: 8084
  tomcat:
    uri-encoding: utf-8


# Spring配置
spring:
#  # 模板引擎
#  thymeleaf:
#    mode: HTML
#    encoding: utf-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html #模板后缀
    encoding: UTF-8 #编码
    cache: false
    mode: HTML5
    enabled: true


#    mode: HTML #模板

#    servlet:
#      content-type: text/html